name: Build CKAN Docker 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feat/continous-deploy

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
      
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    -  name: NGINX build and push to Docker Hub
       uses: docker/build-push-action@v2
       with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: false
          tags: folhesgabriel/ckan-docker-nginx:latest

    -  name: PostgreSQL build and push to Docker Hub
       uses: docker/build-push-action@v2
       with:
          context: ./postgresql
          file: ./postgresql/Dockerfile
          push: false
          tags: folhesgabriel/ckan-docker-postgresql:latest

    -  name: CKAN build and push to Docker Hub
       uses: docker/build-push-action@v2
       with:
          context: ./ckan
          file: ./ckan/Dockerfile
          push: false
          tags: folhesgabriel/ckan-docker-ckan:latest
      