name: Build and Push Images to Azure Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - feat/production-setup


      
jobs: 
  build_push_acs:  
    runs-on: ubuntu-latest
    steps: 
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_SP_APP_ID }}
        password: ${{ secrets.ACR_SP_PASSWORD }}

    - name: NGINX build and push to ACR
      uses: docker/build-push-action@v5
      with:
         context: ./nginx
         file: ./nginx/Dockerfile
         tags: ${{ secrets.ACR_LOGIN_SERVER }}/ckan-nginx:latest

    - name: PostgreSQL build and push to ACR
      uses: docker/build-push-action@v5
      with:
         context: ./postgresql
         file: ./postgresql/Dockerfile
         tags: ${{ secrets.ACR_LOGIN_SERVER }}/ckan-postgresql:latest

    - name: CKAN build and push to ACR
      uses: docker/build-push-action@v5
      with:
         context: ./ckan
         file: ./ckan/Dockerfile
         tags: ${{ secrets.ACR_LOGIN_SERVER }}/ckan-ckan:latest